/*
 * Copyright (c) 2019-2020 TRUSTONIC LIMITED
 * All rights reserved
 *
 * The present software is the confidential and proprietary information of
 * TRUSTONIC LIMITED. You shall not disclose the present software and shall
 * use it only in accordance with the terms of the license agreement you
 * entered into with TRUSTONIC LIMITED. This software may be subject to
 * export or import laws in certain countries.
 */
/* File autogenerated at 2020-07-13 16:16:01.108673
 * To prevent regeneration on next build, change file length or remove the GeneratedFileSize line at end of file
 */

#ifndef _CADIGITALID_H_
#define _CADIGITALID_H_


#ifdef __cplusplus
extern "C" {
#endif


#include "tee_client_api.h"

TEEC_Result initTA(uint32_t *returnOrigin,int8_t*  buf_input,uint32_t  len_input);

TEEC_Result reset(uint32_t *returnOrigin,uint32_t  input);

TEEC_Result beginActivation(uint32_t *returnOrigin,int8_t*  buf_output,uint32_t *len_output);

TEEC_Result getActivationServerEncryptionKey(uint32_t *returnOrigin,int8_t*  buf_output,uint32_t *len_output);

TEEC_Result signAcquisition(uint32_t *returnOrigin,int8_t*  buf_input,uint32_t  len_input,int8_t*  buf_output,uint32_t *len_output);

TEEC_Result executeScript(uint32_t *returnOrigin,int8_t*  buf_input,uint32_t  len_input,int8_t*  buf_output,uint32_t *len_output,int8_t*  buf_outputCose,uint32_t *len_outputCose);

TEEC_Result getListOfIDsAndMetaData(uint32_t *returnOrigin,int8_t*  buf_output,uint32_t *len_output);

TEEC_Result selectIDForNFC(uint32_t *returnOrigin,int8_t*  buf_refID,uint32_t  len_refID,int8_t*  buf_output,uint32_t *len_output);

TEEC_Result processNFCCommand(uint32_t *returnOrigin,int8_t*  buf_request,uint32_t  len_request,int8_t*  buf_response,uint32_t *len_response);

TEEC_Result closeDownNFCSession(uint32_t *returnOrigin);

TEEC_Result getQRCode(uint32_t *returnOrigin,int8_t*  buf_refID,uint32_t  len_refID,uint32_t  responseType,int8_t*  buf_response,uint32_t *len_response);


#ifdef __cplusplus
}
#endif


#endif
/* Autogenerated file. To prevent regeneration on next build, change file length or remove line below */
/* To force regeneration, delete the file */
/* GeneratedFileSize=2115  */
